/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.example.java-library-conventions")
}

dependencies {
    api(project(":list"))
}

java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(17))
}
