/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.4.2/userguide/building_java_projects.html
 */

plugins {
    `java-library`
    groovy
}

repositories {
    mavenCentral()
}

dependencies {
    api(libs.math)
    implementation(libs.guava)

    testImplementation(libs.spock)
    testImplementation(libs.groovy.core)
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
