/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.4.2/userguide/building_java_projects.html
 */

plugins {
    `java-library`
    groovy
    alias(libs.plugins.spotbugs)
    `java-test-fixtures`
}

repositories {
    mavenCentral()
}

dependencies {
    api(libs.math)
    implementation(libs.guava)
    runtimeOnly(micronaut.logback)

    testFixturesApi(libs.groovy.core)

    testImplementation(libs.spock)
    testImplementation(libs.groovy.core)
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
        vendor.set(JvmVendorSpec.ADOPTIUM)
    }
}

testing {
    suites {
        val integrationTest by registering(JvmTestSuite::class) {
            dependencies {
                implementation(project)
                implementation(project.dependencies.testFixtures(project))
            }
            useJUnitJupiter()
            targets {
                all {
                    testTask.configure {
                        shouldRunAfter(tasks.test)
                    }
                }
            }
        }

        val test by getting(JvmTestSuite::class) {
            useJUnitJupiter()
            targets {
                all {
                    testTask.configure {
                        javaLauncher.set(javaToolchains.launcherFor{
                            languageVersion.set(JavaLanguageVersion.of(17))
                        })
                    }
                }
            }
        }
    }
}