/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package example

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

class FileProcessingPluginTest {

    @Test
    fun `plugin registers task`() {
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("file-processing")
        assertNotNull(project.tasks.findByName("processFiles"))
    }
}
